apiVersion: apps/v1
kind: Deployment
metadata:
  name: zy-app
  namespace: zyproj
  labels:
    app: zy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zy-app
  template:
    metadata:
      labels:
        app: zy-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: zy-app-svc
  namespace: zyproj
  labels:
    app: zy-app
spec:
  selector:
    app: zy-app
  ports:
    - name: http
      port: 8081         # Service port exposed inside the cluster
      targetPort: 80     # Container port in the pod
  type: ClusterIP        # Default; change to NodePort/LoadBalancer if needed

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.tls: "false"
    ingress.kubernetes.io/rewrite-target: /
  name: zy-app-ingress
  namespace: zyproj
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: zy-app-svc
            port:
              number: 8081
        path: /zy
        pathType: Prefix
